corpora/corpora/urls.py
# -*- coding: utf-8 -*-
"""corpora URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
	https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
	1. Add an import:  from my_app import views
	2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
	1. Add an import:  from other_app.views import Home
	2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
	1. Import the include() function: from django.conf.urls import url, include
	2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
#from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _

from django.contrib import admin

from corpora import views
from people import views as people_views


urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^', include('corpus.urls',namespace='corpus')),

	url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^admin/', admin.site.urls),
	url(r'^account/', include('allauth.urls')),


	url(_(r'^people/'), include('people.urls', namespace='people')),

	# url(r'^$', cache_on_auth(settings.SHORT_CACHE)(views.home), name='home'),
]


# I think it's better we store language preference in cookie and not do url redirects
# urlpatterns += i18n_patterns(
#     url( _(r'^people/'), include('people.urls', namespace='people')),
# )
#prefix_default_language=True

corpora/corpus/urls.py
from django.conf.urls import url, include

from corpus import views

urlpatterns = [
	url(r'^record/', views.record, name='record'),
	url(r'^submit_recording/', views.submit_recording, name='submit_recording'),
	url(r'^failed_submit/', views.failed_submit, name='failed_submit'),
]

corpora/people/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include

from people import views

urlpatterns = [

    url(r'^profile', views.profile, name='profile'),

	url(r'^choose_language', views.choose_language, name='choose_language'),
	url(r'^set_language', views.set_language, name='set_language'),
	# url(r'^(?P<uuid>[\w-]+)', views.person, name='person'),
	url(r'^demographics', views.create_demographics, name='demographics'),
	url(r'^create_account', views.create_user, name='create_user'),

]

corpora/corpora/views.py
from django.template.context import RequestContext
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as auth_login
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.conf import settings

from people.helpers import get_unknown_languages

from corpus import views

def home(request):
	if request.user.is_authenticated():
		return redirect('people:profile')
	else:


		context = {
			'request': request,
			'languages': get_unknown_languages(None),
		}

		return render(request, 'corpora/home.html', context)
		#return redirect('account/login')

corpora/corpora/templates/corpora/base.html
{% load static %}
{% load sekizai_tags %}
{% load compress %}
{% load sass_tags %}

<!DOCTYPE html>

<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width" />

  <title>corpora.io</title>

  <link href="https://fonts.googleapis.com/css?family=Comfortaa:300,400,700|Poiret+One&amp;subset=latin-ext" rel="stylesheet">
  {# Uses sekizai to load all css at start of page & compressor to minify it #}
  {% render_block "css" postprocessor "compressor.contrib.sekizai.compress" %}

  {# CSS files to load & combine #}
  {% addtoblock "css" %}
    <link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% sass_src 'corpora/css/main.scss' %}" rel="stylesheet" type="text/css" />
    <link href="{% sass_src 'corpora/css/nav.scss' %}" rel="stylesheet" type="text/css" />
  {% endaddtoblock %}


  {% addtoblock "js" %}
    <script type="text/javascript" src='{% static 'jquery/dist/jquery.min.js' %}'></script>
    <script type="text/javascript" src='{% static 'jquery-ui/jquery-ui.min.js' %}'></script>
    <script type="text/javascript" src='{% static 'corpora/js/transitions.js' %}'></script>
  {% endaddtoblock %}
  
</head>

<body>

  <nav class="navbar navbar-static-top">
    <div class="container">
      <div class="nav">
        {% block navbuttons %}{% endblock %}
      </div>
    </div>
  </nav>

  <div class="content">
    {% block content %}
    {% endblock%}
  </div>

  {# Uses sekizai to load all js at end of page #}
  {% render_block "js" %}
</body>

</html>

corpora/corpora/templates/corpora/base_landing.html
{% load static %}
{% load sekizai_tags %}
{% load compress %}
{% load sass_tags %}

<!DOCTYPE html>

<html lang="en">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width" />

	<title>corpora.io</title>

	<link href="https://fonts.googleapis.com/css?family=Comfortaa:300,400,700|Open+Sans|Poiret+One&amp;subset=latin-ext" rel="stylesheet">
	{# Uses sekizai to load all css at start of page & compressor to minify it #}
	{% render_block "css" postprocessor "compressor.contrib.sekizai.compress" %}

	{# CSS files to load & combine #}
	{% addtoblock "css" %}
		<link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% sass_src 'corpora/css/main.scss' %}" rel="stylesheet" type="text/css" />
		<link href="{% sass_src 'corpora/css/nav.scss' %}" rel="stylesheet" type="text/css" />
	{% endaddtoblock %}


	{% addtoblock "js" %}
		<script type="text/javascript" src='{% static 'jquery/dist/jquery.min.js' %}'></script>
		<script type="text/javascript" src='{% static 'jquery-ui/jquery-ui.min.js' %}'></script>
		<script type="text/javascript" src='{% static 'corpora/js/transitions.js' %}'></script>
	{% endaddtoblock %}
	
</head>

<body>

	<div class="col-lg-6 col-md-5 col-sm-5 col-xs-6 navbuttons">
		{% block navbuttons %}
		{% endblock %}    
	</div>


	<div class="content">
		{% block content %}
		{% endblock %}
	</div>
	{# Uses sekizai to load all js at end of page #}
	{% render_block "js" %}
</body>

</html>

corpora/corpora/templates/corpora/home.html
{% extends 'corpora/base_landing.html' %}

{% load static %}
{% load sekizai_tags %}
{% load compress %}
{% load sass_tags %}
{% load i18n %}

{% block content %}

{% addtoblock "css" %}
<link href="{% sass_src 'corpora/css/home.scss' %}" rel="stylesheet" type="text/css" />
{% endaddtoblock %}

<div class="jumbotron">
  <div class="container"><div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <h1>corpora.io</h1>
      <h3 class="sub-header-text">{% blocktrans %}teaching computers indigenous languages{% endblocktrans %}</h3>
    </div>
  </div></div>
</div>

<div class="content">
  <div class="container">
    <div class="row"> 

<!--       <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 right-card pull-right">
        <p style="text-align: center;">
        <a href="{% url 'account_login' %}">Login</a>
        </p>
      </div>  -->

      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 left-card">
        <p class="dropcase">{% blocktrans %}Corpora.io is an opensource app designed to collect spoken 
        corpora&mdash;vocal recordings&mdash;to train computers to understand 
        spoken languages through machine learning. This project started in an effort
        to automate the transcription of thousands of hours of te reo Māori archives
        available at <a href="https://tehiku.nz">tehiku.nz</a> and to enhance access 
        to Māori media. We also wanted to bring te reo Māori, and other indigenous languages,
        to voice operated digital assistants like Siri.{% endblocktrans %}</p>

        <div>
          <h2>{% trans "Available Languages" %}</h2>
          <p>{% blocktrans %}Translations for corpora.io are provided in the following langauges:{% endblocktrans %}</p>
          <ul>
          {% for lang_code in languages %}
          {% get_language_info for lang_code as lang %}
          <li>{{ lang.name_translated }}</li>
          {% endfor %}
          </ul>

          <p>Add another language by <a href="https://github.com/TeHikuMedia/corpora/tree/translate">translating</a> this app.</p>
          </div>

      </div>


      <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 right-card">
        <span></span>
        <p></p>
      </div>


    </div>
  </div>
</div>

<div class="footer">
  <div class="container">
    <div class="row"> 
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-6">
          <h4>Site Map</h4>
          <p><a href="{% url 'account_login' %}">Login</a></p>
          <!-- <p><a href="{% url 'account_signup' %}">Sign-Up</a></p>
          <p><a href="{% url 'people:profile' %}">Profile</a></p>
          <p><a href="{% url 'corpus:record' %}">Record</a></p> -->
        </div>
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-6">
          <h4>Get Involved</h4>
          <p><a href="https://github.com/TeHikuMedia/corpora">GitHub</a></p>
          <p><a href="https://github.com/TeHikuMedia/corpora/tree/translate">Translate</a></p>
          <p>Wānanga</p>        </div>
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-6">
          <h4>Supporters</h4>
          <p><a href="https://tehiku.nz">Te Hiku Media</a></p>
          <p><a href="https://www.dragonfly.co.nz/">Dragonfly Data Science</a></p>
          <p><a href="http://www.tepunahamatatini.ac.nz/">Te Punaha Matatini</a></p>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-6">
          <h4>Powered by</h4>
          <p><a href="https://www.djangoproject.com/">Django</a></p>
        </div>

    </div>
  </div>
</div>

{% addtoblock "js" %}

{% endaddtoblock %}
{% endblock %}

corpora/corpora/templates/corpora/logged_in_nav_buttons.html
{% load account %}
{% load i18n %}
{% load socialaccount %}
{% load sekizai_tags %}
{% load static %}
{% load language %}


{% addtoblock "css" %}
<link rel="stylesheet" href="{% static 'components-font-awesome/css/font-awesome.min.css' %}">
{% endaddtoblock %}

<div class="brand">
    <a href="/">
        corpora.io
    </a>
</div>

{% if request.user.is_authenticated %}

<div>
<a href="#" onclick="$('form[id=logout]').submit();">
    <i class="fa fa-fw fa-lg fa-sign-out"></i>
    <div>{% trans 'Log Out' %}</div>
</a>        
</div>   

<div>
<a href="{% url 'people:profile' %}" >
    <i class="fa fa-lg fa-fw fa-user"></i>
    <div >{% trans 'Profile' %}</div>
</a>
</div>

{% if request.user.is_staff %}
<div>
<a href="/admin" >
    <i class="fa fa-lg fa-fw fa-cogs"></i>
    <div>{% trans 'Admin' %}</div>
</a>
</div>
{% endif %}


<!-- <div>
<a href="#" class="">
    <i class="fa fa-fw fa-lg fa-edit"></i>
    <div >{% trans 'Edit Info' %}</div>
</a>
</div> -->


<div class="dropdown">
{% get_current_language request as current_language %}
{% get_known_languages request as known_languages %}
{% if known_languages %}
<!-- <div class="btn-group"> -->
  <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="fa fa-fw fa-lg fa-language"></i>
    <div>

    {% get_language_info for current_language as lang %}
    {% trans 'Language' %} <span class="caret"></span>
    </div>
  </a>

  <ul class="dropdown-menu">
    {% comment %}Instead we'll want to get the KnownLanguages for the Person {% endcomment %}
    {% get_language_info_list for known_languages as languages %}
    {% for lang in languages %}
        <li><a href="#" onclick="$('form[id=language_selector_form] input[name=language]').val('{{lang.code}}');$('form[id=language_selector_form]').submit();">
        {% if lang.code == current_language %}<i class="fa fa-fw fa-check"></i>{% endif %}
        {{ lang.name_translated }}</a></li>
    {% endfor %}
        <li><a href="{% url 'people:choose_language' %}?next=people:profile">Add/Edit Language</a></li>
  </ul>

{% endif %}
</div>
    


<div>
<a href="{% url 'corpus:record' %}" >
    <i class="fa fa-lg fa-fw fa-microphone"></i>
    <div >{% trans 'Record' %}</div>
</a>
</div>







<form method="post" action="{% url 'account_logout' %}" style="display: inline-block;" id="logout" class="hidden" >
    
        {% csrf_token %}
        {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
        {% endif %}
    
</form>
<form class="hidden" action="{% url 'people:set_language' %}" method="post" id="language_selector_form" >
    
        {% csrf_token %}
        <input name="language" type="hidden" value="{{current_language}}" />
    
</form>

{% endif %}

{% addtoblock "js" %}
    <script type="text/javascript" src='{% static 'bootstrap/dist/js/bootstrap.min.js' %}'></script>
{% endaddtoblock %}