corpora/corpora/urls.py
# -*- coding: utf-8 -*-
"""corpora URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
	https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
	1. Add an import:  from my_app import views
	2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
	1. Add an import:  from other_app.views import Home
	2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
	1. Import the include() function: from django.conf.urls import url, include
	2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
#from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _

from django.contrib import admin

from corpora import views
from people import views as people_views


urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^', include('corpus.urls',namespace='corpus')),

	url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^admin/', admin.site.urls),
	url(r'^account/', include('allauth.urls')),


	url(_(r'^people/'), include('people.urls', namespace='people')),

	# url(r'^$', cache_on_auth(settings.SHORT_CACHE)(views.home), name='home'),
]


# I think it's better we store language preference in cookie and not do url redirects
# urlpatterns += i18n_patterns(
#     url( _(r'^people/'), include('people.urls', namespace='people')),
# )
#prefix_default_language=True

corpora/corpus/urls.py
from django.conf.urls import url, include

from corpus import views

urlpatterns = [
	url(r'^record/', views.record, name='record'),
	url(r'^submit_recording/', views.submit_recording, name='submit_recording'),
	url(r'^failed_submit/', views.failed_submit, name='failed_submit'),
]

corpora/corpus/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from corpora.settings import LANGUAGES, LANGUAGE_CODE


class Sentence(models.Model):
    text = models.CharField(help_text='The sentence to be spoken.',max_length=250, unique=True)
    language = models.CharField(choices=LANGUAGES, max_length=16, default=LANGUAGE_CODE)

    class Meta:
        verbose_name = 'Sentence'
        verbose_name_plural = 'Sentences'

    def __unicode__(self):
        return self.text

class Recording(models.Model):
    person = models.ForeignKey('people.Person')
    sentence = models.ForeignKey('Sentence')
    audio_file = models.FileField()

    class Meta:
        verbose_name = 'Recording'
        verbose_name_plural = 'Recordings'
        unique_together = (("person","sentence"),)

    def __unicode__(self):
        return self.sentence.text + " by " + self.person.full_name

corpora/corpus/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from django.template.context import RequestContext
from django.forms import modelform_factory
from django.http import HttpResponse
from django.urls import reverse, resolve
from django.core.exceptions import ValidationError
import json

from corpus.models import Recording, Sentence
from people.models import Person
from .helpers import get_next_sentence
from people.helpers import get_or_create_person_from_user

import logging
logger = logging.getLogger('corpora')

def submit_recording(request):
	return render(request, 'corpus/submit_recording.html')

def failed_submit(request):
	return render(request, 'corpus/failed_submit.html')

def record(request):
	# Get the person object from the user

	if not request.user.is_authenticated(): return redirect(reverse('account_login'))

	person = get_or_create_person_from_user(request.user)

	if request.method == 'GET':
		if request.GET.get('sentence',None):
			sentence = Sentence.objects.get(pk=request.GET.get('sentence'))
		else:
			sentence = get_next_sentence(request)
			if sentence == None:
				return redirect('people:profile')

	# Generate a form model from the Recording model
	RecordingFormAJAX = modelform_factory(Recording, fields='__all__')

	# If page receives POST request, save the submitted audio data as a recording model
	if request.method == 'POST' and request.is_ajax():

		# Create a form from the Recording Form model
		form = RecordingFormAJAX(request.POST, request.FILES)

		# If the form is valid, save the new model and send back an OK HTTP Response
		if form.is_valid():
			recording = form.save()
			recording.save()
			return HttpResponse(
				json.dumps({
					'success': True,
					'message': "Thank you for submitting a recording! Here's another sentence for you to record."
				}), 
				content_type='application/json',
			)

		# If the form is not valid, sent a 400 HTTP Response
		else:
			# errors = form.errors			
			response = HttpResponse(
				json.dumps({
						'err': "Sorry, your recording did not save."
					}),
				content_type='application/json'
			)
			response.status_code = 400

			return response
		
	# Load up the page normally with request and object context
	context = {'request': request,
		'person': person,
		'sentence': sentence
		}

	return render(request, 'corpus/record.html', context)

corpora/corpus/templates/corpus/base.html
{% extends "corpora/base.html" %}
{% load account %}
{% load i18n %}
{% load socialaccount %}
{% load sekizai_tags %}
{% load static %}
{% load language %}

{% block navbuttons %}
{% include 'corpora/logged_in_nav_buttons.html' %}
{% endblock %}

corpora/corpus/templates/corpus/failed_submit.html
{% extends 'corpora/base.html' %}

{% block content %}

FAILURE

{% endblock %}

corpora/corpus/templates/corpus/record.html
{% extends 'corpus/base.html' %}

{% load static %}
{% load sekizai_tags %}
{% load compress %}
{% load sass_tags %}


{% block content %}
	{% addtoblock "css" %}
		<link href="{% sass_src 'corpus/css/record.scss' %}" rel="stylesheet" type="text/css" />
	{% endaddtoblock %}

	<div class="container">
		<div class="row" id="recorder-container">
			<div class="col-xs-12 col-sm-12 col-md-1 col-lg-1"></div>
			<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10">
				<div id="status-message" class="error-message" style="display: none;"><h2></h2></div>

				<h2>Record this sentence in Te Reo: </h2>
				{{sentence.text}}</br>
				<h3>When you're ready, press the REC button to record the sentence. When you're done, press the button again to stop the recording.
				When you have a recording you are satisfied with, press "Next."
				</h3>

				<div class="circle-button-container">
					<div class="circle background-circle">
						<a href="javascript:void(0)" id="record-button">
							<div class="circle foreground-circle unclicked-circle record">
								<div class="circle-text record">REC</div>
								<div class="stop-square"></div>
							</div>
						</a>

						<a href="javascript:void(0)" id="play-button">
							<div class="circle foreground-circle unclicked-circle play">
								<div class="play-triangle"></div>
							</div>
						</a>
					</div>
				</div>


				<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6" id="redo" style="display: none;" >
					<a href="javascript:void(0)">
						<div class="button">
							Reset
						</div>
					</a>
				</div>

				<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6" id="save" style="display: none;">
					<a href="javascript:void(0)">
						<div class="button">
							Save
						</div>
					</a>
				</div>

				{% comment %}					
				<a href="javascript:void(0)" id="next" style="display: none;">
					<div class="button">
						Next
					</div>
				</a>
				{% endcomment %}
				
			</div>
			<div class="col-xs-12 col-sm-12 col-md-1 col-lg-1"></div>
		</div>
	</div>

		{% comment %}
		<small> Does this recording sound accurate? If so, press Next. If not, go back and fix it with Back.</small>

		<a href="{% url 'corpus:submit_recording' %}">
			<div class="button submit-audio">
				Submit
			</div>
		</a>
		{% endcomment %}
	</div>
	
	<audio id="play-audio" style="display: none; width: 0px; height: 0px">
	</audio>

	{% addtoblock "js" %}
		<script>
			var person_pk = "{{person.pk}}";
			var sentence_pk = "{{sentence.pk}}";
			var encoder_path = "{% static 'opus-recorderjs/build/encoderWorker.min.js' %}";
		</script>

		<script type="text/javascript" src='{% static 'opus-recorderjs/build/recorder.min.js' %}'></script>
		<script type="text/javascript" src='{% static 'corpora/js/recorder.storepage.js' %}'></script>
		<script type="text/javascript" src='{% static 'corpus/js/ajax.post.js' %}'></script>
		<script type="text/javascript" src='{% static 'corpus/js/record.js' %}'></script>

	{% endaddtoblock %}
{% endblock %}

corpora/corpus/templates/corpus/submit_recording.html
{% extends 'corpora/base.html' %}

{% block content %}

SAVE THE RECORDING!!

{% endblock %}